# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


class Tweet(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    created_at = ... # type: builtin___int
    user_id = ... # type: builtin___int
    text = ... # type: typing___Text
    lang = ... # type: typing___Text
    tweet_id = ... # type: builtin___int
    user_name = ... # type: typing___Text

    def __init__(self,
        *,
        created_at : typing___Optional[builtin___int] = None,
        user_id : typing___Optional[builtin___int] = None,
        text : typing___Optional[typing___Text] = None,
        lang : typing___Optional[typing___Text] = None,
        tweet_id : typing___Optional[builtin___int] = None,
        user_name : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> Tweet: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"created_at",u"lang",u"text",u"tweet_id",u"user_id",u"user_name"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"created_at",b"created_at",u"lang",b"lang",u"text",b"text",u"tweet_id",b"tweet_id",u"user_id",b"user_id",u"user_name",b"user_name"]) -> None: ...
